import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Portfolio Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <Toaster/>
        <main className="bg-zinc-800 w-full min-h-screen sm:h-[calc(100vh-64px)] px-4 md:px-8 p-4 text-white">
        {children}
        </main>
        </body>
    </html>
  );
}
